baseURL = "https://blog.kastori.dev/"
locale = "ko-kr"
title = "kastori"
theme = "stack"
paginate = 10

[params]
    mainSections = ["tech", "til", "log"]
    rssFullContent = true

    [params.footer]
        since = 2026

    [params.dateFormat]
        published = "2006-01-02"
        lastUpdated = "2006-01-02"

    [params.sidebar]
        compact = false
        emoji = "💻"
        subtitle = "풀스택 개발자의 기술 블로그"
        avatar = ""

    [params.article]
        toc = true
        readingTime = true
        headingAnchor = true

        [params.article.license]
            enabled = false

    [params.colorScheme]
        toggle = true
        default = "auto"

    [[params.widgets.homepage]]
        type = "search"

    [[params.widgets.homepage]]
        type = "archives"
        [params.widgets.homepage.params]
            limit = 5

    [[params.widgets.homepage]]
        type = "tag-cloud"
        [params.widgets.homepage.params]
            limit = 10

    [[params.widgets.page]]
        type = "toc"

    [params.opengraph.twitter]
        card = "summary_large_image"

    [params.comments]
        enabled = false

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10
        [menu.main.params]
            icon = "home"

    [[menu.main]]
        identifier = "tech"
        name = "Tech"
        url = "/tech/"
        weight = 20
        [menu.main.params]
            icon = "archives"

    [[menu.main]]
        identifier = "til"
        name = "TIL"
        url = "/til/"
        weight = 30
        [menu.main.params]
            icon = "hash"

    [[menu.main]]
        identifier = "log"
        name = "Log"
        url = "/log/"
        weight = 40
        [menu.main.params]
            icon = "infinity"

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 50
        [menu.main.params]
            icon = "tag"

    [[menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search/"
        weight = 60
        [menu.main.params]
            icon = "search"

    [[menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/kastori1206"
        weight = 70
        [menu.main.params]
            icon = "brand-github"
            newTab = true

[outputs]
    home = ["HTML", "RSS"]
